### ISSUE TITLE
Music Sounded Scratchy/Distorted

### ISSUE THREAD

**Issue by GotDonuts** [ProdunoGamesStudios/SpaceSlog_bugs-and-issues#1]
### Description

On first booting the game the music sounded scratchy and distorted, turning the volume up and down fixed the problem immediately. Rebooting the game and the music is fine, not entirely sure if it was a fluke or something.

### Store affected

Steam

### Operating System

Windows

### Version

0.7.4.11 Alpha

### Is it something that used to work before?

No

### Extra information

If I had recording software I would have had it running, any suggestions in that department and I will get that installed.
Audio is ran through my HDMI 2 on my video card (RX 5500 XT), if that helps.

### Steps to reproduce

Launch Game

**Comment by produno** [comment]
Ah, turns out the music was 100x louder than it should be when first launching the game -_-.

Fixed now, thanks!
