### ISSUE TITLE
Not enough starting resources

### ISSUE THREAD

**Issue by GotDonuts** [ProdunoGamesStudios/SpaceSlog_bugs-and-issues#4]
### Description

Either things are too expensive or the 3 chunks of ship debris aren't providing enough resources. Attempting to build a thruster to get my pod rolling and I cannot achieve this goal after multiple attempts, I simply do not have enough resources.

### Store affected

Steam

### Operating System

Windows

### Version

0.7.4.11 Alpha

### Is it something that used to work before?

No

### Extra information

Not sure of the first goal, I assumed it was to get rolling so I can start exploring for more resources to continue to expand the ship itself, and provide a better environment for my people. Will try hanging out for a while after gathering the resources to see if anything happens and if it is just me being impatient.

### Steps to reproduce

Start game.

**Comment by produno** [comment]
The start of the game is fairly unbalanced at the moment. The Incidents/Events Ai should help take care of this in the future. Though currently you should try and ensure  your pawns are surviving before attempting to travel. Various events will help you gain resources at the start of the game.
