### ISSUE TITLE
Scroll Speed

### ISSUE THREAD

**Issue by GotDonuts** [ProdunoGamesStudios/SpaceSlog_bugs-and-issues#5]
**Is your feature request related to a problem? Please describe.**
I am frustrated by the slow speed of moving the camera around, I have been using the middle mouse button as it is faster, but WASD and edge scrolling are painfully slow.

**Describe the solution you'd like**
An option to increase or decrease the scroll speed would be very helpful, that way people can customize the experience to what they would like.

**Describe alternatives you've considered**
Increase the default scroll speed and leave it at that, no customization.

**Additional context**
None available.

**Comment by produno** [comment]
You can hold down Ctrl to scroll faster when using WASD. These hotkeys need to be documented somewhere but will likely also be part of the tutorial.
