### ISSUE TITLE
Some title boxes are huge compared to others.

### ISSUE THREAD

**Issue by GotDonuts** [ProdunoGamesStudios/SpaceSlog_bugs-and-issues#6]
### Description

I noticed on a load of a save game that the title boxes are huge on everything except the water and one of my crew that is outside the ship gathering debris.

### Store affected

Steam

### Operating System

Windows

### Version

0.7.4.11 Alpha

### Is it something that used to work before?

Yes

### Extra information

Displayed correctly before reloading the game, will attempt again and see if issue still exists. Attaching an image.
![Titlebox](https://github.com/ProdunoGamesStudios/SpaceSlog_bugs-and-issues/assets/158860800/273b2424-fe60-4df5-aaf4-d869b0045a73)

- Problem did not persist through reload of the game after exiting.

### Steps to reproduce

Save game and exit the program completely, Restart and reload the game.

**Comment by GotDonuts** [comment]
Just reporting that I am seeing this randomly happening in the latest version.

**Comment by produno** [comment]
I have added a potential fix for the next build. Will need testing more thoroughly however before i close this issue.
