### ISSUE TITLE
Space Scrap not saved on reload

### ISSUE THREAD

**Issue by GotDonuts** [ProdunoGamesStudios/SpaceSlog_bugs-and-issues#7]
### Description

I made a save with some crew that I liked right out of the gate. When things went south due to my poor planning I reloaded the save but the chunks of ship around the escape pod no longer where in space, forcing me to start over again with a new crew.

### Store affected

Steam

### Operating System

Windows

### Version

0.7.4.12 Alpha

### Is it something that used to work before?

No idea

### Extra information

[Donuts.json](https://github.com/ProdunoGamesStudios/SpaceSlog_bugs-and-issues/files/15445154/Donuts.json)
Attached is my save game, where the issue occurs. 

### Steps to reproduce

Start new game, save then reload game.

**Comment by produno** [comment]
Fixed, thanks.
