### ISSUE TITLE
Stockpile Bug

### ISSUE THREAD

**Issue by GotDonuts** [ProdunoGamesStudios/SpaceSlog_bugs-and-issues#8]
### Description

The stockpile allowed diamonds to enter it. I had only toggled survival meals to arrive in it, in order to move them out of the way of construction.

### Store affected

Steam

### Operating System

Windows

### Version

0.7.4.12 Alpha

### Is it something that used to work before?

No idea

### Extra information

![Stockpile](https://github.com/ProdunoGamesStudios/SpaceSlog_bugs-and-issues/assets/158860800/4e95d4f1-5a61-41e7-88b0-952c68eaac35)

Here is a picture of the stockpile with the settings. It was just after a resource drop arrived not sure if the drop dropped the resources directly into the stockpile.

### Steps to reproduce

Not sure how to reproduce this beyond making a stockpile for things to go into and seeing if the error occurs again.

**Comment by produno** [comment]
Yeah, currently the resources just try and find a place on the ship, whether thats a stockpile or not.
