### ISSUE TITLE
Larger Escape Pod

### ISSUE THREAD

**Issue by GotDonuts** [ProdunoGamesStudios/SpaceSlog_bugs-and-issues#9]
A one row larger escape pod would solve issues with having to juggle a stockpile around while getting the basic devices setup for survival, saving some time and hopefully increasing survival chance. Not asking for a huge escape vessel but having one more row would free up having to create several stockpiles to get the vent/generator and life support online.

**Comment by produno** [comment]
I would prefer to try and give people more time and resources to be able to expand it themselves if they need to. Something i have done in the latest builds, so we will see how this pans out.
